export const OPEN_SIDEBAR = 'OPEN_SIDEBAR';
export const CLOSE_SIDEBAR = 'CLOSE_SIDEBAR';

export const FETCH_STARTED = 'PATIENT/FETCH_STARTED';
export const FETCH_SUCCESS = 'PATIENT/FETCH_SUCCESS';
export const FETCH_FAILURE = 'PATIENT/FETCH_FAILURE';